<?php
declare(strict_types=1);

function app_ensure_system_settings_table(PDO $pdo): void
{
    static $ensured = false;
    if ($ensured) {
        return;
    }
    $ensured = true;

    $pdo->exec(
        "CREATE TABLE IF NOT EXISTS system_settings (
            setting_key VARCHAR(100) NOT NULL,
            setting_value LONGTEXT NOT NULL,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (setting_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
    );
}

/**
 * Returns true only when $name is a safe SQL identifier:
 * starts with a letter or underscore, contains only letters/digits/underscores,
 * and is at most 64 characters (MySQL identifier limit).
 * Used to guard dynamic table/column names before interpolating into SQL.
 */
function app_schema_is_safe_identifier(string $name): bool
{
    return (bool)preg_match('/^[a-zA-Z_][a-zA-Z0-9_]{0,63}$/', $name);
}

function app_table_is_queryable(PDO $pdo, string $table): bool
{
    if (!app_schema_is_safe_identifier($table)) {
        return false;
    }
    try {
        $pdo->query('SELECT 1 FROM `' . $table . '` LIMIT 1');
        return true;
    } catch (Throwable $e) {
        return false;
    }
}

function app_column_is_queryable(PDO $pdo, string $table, string $column): bool
{
    if (!app_schema_is_safe_identifier($table) || !app_schema_is_safe_identifier($column)) {
        return false;
    }
    try {
        $pdo->query('SELECT `' . $column . '` FROM `' . $table . '` LIMIT 1');
        return true;
    } catch (Throwable $e) {
        return false;
    }
}

function app_orders_unique_code_index_exists(PDO $pdo): bool
{
    try {
        $stmt = $pdo->query("SHOW INDEX FROM orders WHERE Key_name = 'uq_orders_order_code'");
        return (bool)($stmt && $stmt->fetch());
    } catch (Throwable $e) {
        return false;
    }
}

function app_orders_idempotency_table_is_queryable(PDO $pdo): bool
{
    return app_table_is_queryable($pdo, 'order_request_idempotency');
}

function app_ensure_order_request_idempotency_table(PDO $pdo): void
{
    static $ensured = false;
    if ($ensured) {
        return;
    }
    $ensured = true;

    if (!app_orders_idempotency_table_is_queryable($pdo)) {
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS order_request_idempotency (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                client_request_id VARCHAR(64) NOT NULL,
                method VARCHAR(10) NOT NULL,
                endpoint VARCHAR(120) NOT NULL,
                actor_user_id VARCHAR(64) NULL,
                order_id BIGINT UNSIGNED NULL,
                response_json LONGTEXT NOT NULL,
                status_code SMALLINT UNSIGNED NOT NULL DEFAULT 200,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                UNIQUE KEY uq_order_request_idempotency_client_request_id (client_request_id),
                KEY idx_order_request_idempotency_actor_created (actor_user_id, created_at),
                KEY idx_order_request_idempotency_order (order_id)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
        );
    }
}

function app_validate_client_request_id($value): ?string
{
    if ($value === null) {
        return null;
    }

    $raw = trim((string)$value);
    if ($raw === '') {
        return null;
    }

    // Expected UUIDv4 generated by frontend offline queue/idempotency flow.
    if (!preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i', $raw)) {
        app_json([
            'success' => false,
            'error' => 'Invalid clientRequestId format.',
            'code' => 'invalid_client_request_id',
        ], 400);
    }

    return strtolower($raw);
}

function app_idempotency_actor_user_id(?array $actor): ?string
{
    if (!is_array($actor)) {
        return null;
    }
    $id = trim((string)($actor['id'] ?? ''));
    return $id === '' ? null : $id;
}

function app_find_idempotent_order_request(
    PDO $pdo,
    string $clientRequestId,
    string $method,
    string $endpoint,
    ?array $actor
): ?array {
    app_ensure_order_request_idempotency_table($pdo);

    $stmt = $pdo->prepare(
        'SELECT client_request_id, method, endpoint, actor_user_id, order_id, response_json, status_code
         FROM order_request_idempotency
         WHERE client_request_id = :client_request_id
         LIMIT 1'
    );
    $stmt->execute(['client_request_id' => $clientRequestId]);
    $row = $stmt->fetch();
    if (!$row) {
        return null;
    }

    $storedMethod = strtoupper((string)($row['method'] ?? ''));
    $storedEndpoint = (string)($row['endpoint'] ?? '');
    $storedActorUserId = $row['actor_user_id'] !== null ? (string)$row['actor_user_id'] : null;
    $currentActorUserId = app_idempotency_actor_user_id($actor);

    if ($storedMethod !== strtoupper($method) || $storedEndpoint !== $endpoint || $storedActorUserId !== $currentActorUserId) {
        app_json([
            'success' => false,
            'error' => 'clientRequestId has already been used for a different request.',
            'code' => 'client_request_id_conflict',
        ], 409);
    }

    return [
        'statusCode' => max(100, min(599, (int)($row['status_code'] ?? 200))),
        'payload' => json_decode((string)($row['response_json'] ?? ''), true),
    ];
}

function app_store_idempotent_order_request_response(
    PDO $pdo,
    string $clientRequestId,
    string $method,
    string $endpoint,
    ?array $actor,
    ?int $orderId,
    array $payload,
    int $statusCode = 200
): void {
    app_ensure_order_request_idempotency_table($pdo);
    $encoded = json_encode($payload, JSON_UNESCAPED_UNICODE);
    if ($encoded === false) {
        return;
    }

    $stmt = $pdo->prepare(
        'INSERT INTO order_request_idempotency (
            client_request_id, method, endpoint, actor_user_id, order_id, response_json, status_code
         ) VALUES (
            :client_request_id, :method, :endpoint, :actor_user_id, :order_id, :response_json, :status_code
         )'
    );

    try {
        $stmt->execute([
            'client_request_id' => $clientRequestId,
            'method' => strtoupper($method),
            'endpoint' => $endpoint,
            'actor_user_id' => app_idempotency_actor_user_id($actor),
            'order_id' => $orderId,
            'response_json' => $encoded,
            'status_code' => max(100, min(599, $statusCode)),
        ]);
    } catch (Throwable $e) {
        // Idempotency store must not break business response.
    }
}

function app_ensure_orders_table(PDO $pdo): void
{
    static $ensured = false;
    if ($ensured) {
        return;
    }
    $ensured = true;

    $ordersTableExists = app_table_is_queryable($pdo, 'orders');
    if (!$ordersTableExists) {
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS orders (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                order_code VARCHAR(64) NOT NULL,
                customer_name VARCHAR(200) NOT NULL,
                phone VARCHAR(40) NOT NULL,
                order_date VARCHAR(40) NOT NULL,
                total BIGINT NOT NULL DEFAULT 0,
                status ENUM('pending','processing','delivered','archived') NOT NULL DEFAULT 'pending',
                items_json LONGTEXT NOT NULL,
                order_meta_json LONGTEXT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                UNIQUE KEY uq_orders_order_code (order_code),
                KEY idx_orders_status (status),
                KEY idx_orders_created_at (created_at)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
        );
    }

    try {
        $stmt = $pdo->query("SHOW COLUMNS FROM orders LIKE 'order_meta_json'");
        if (!$stmt || !$stmt->fetch()) {
            $pdo->exec("ALTER TABLE orders ADD COLUMN order_meta_json LONGTEXT NULL AFTER items_json");
        }
    } catch (Throwable $e) {
        // Keep runtime compatibility if alter is not possible.
    }

    try {
        if (!app_orders_unique_code_index_exists($pdo)) {
            $pdo->exec("ALTER TABLE orders ADD UNIQUE KEY uq_orders_order_code (order_code)");
        }
    } catch (Throwable $e) {
        // Keep runtime compatibility if alter is not possible.
    }

    if (function_exists('app_ensure_orders_customer_columns')) {
        app_ensure_orders_customer_columns($pdo);
    }
}

/**
 * Returns the first candidate column that exists in the orders table, or null if none found.
 * Tries SHOW COLUMNS first, then falls back to a live query probe.
 */
function app_find_orders_column(PDO $pdo, array $candidates): ?string
{
    try {
        app_ensure_orders_table($pdo);
        foreach ($candidates as $col) {
            if (!app_schema_is_safe_identifier((string)$col)) {
                continue;
            }
            $stmt = $pdo->query("SHOW COLUMNS FROM orders LIKE '{$col}'");
            if ($stmt && $stmt->fetch()) {
                return $col;
            }
        }
    } catch (Throwable $e) {
        // Fall through to queryable probe.
    }

    foreach ($candidates as $col) {
        if (app_column_is_queryable($pdo, 'orders', $col)) {
            return $col;
        }
    }

    return null;
}

function app_detect_orders_items_column(PDO $pdo): string
{
    static $detected = null;
    if ($detected !== null) {
        return $detected;
    }
    $detected = app_find_orders_column($pdo, ['items_json', 'items']) ?? 'items_json';
    return $detected;
}

function app_orders_items_column(PDO $pdo): string
{
    return app_detect_orders_items_column($pdo);
}

function app_detect_orders_meta_column(PDO $pdo): ?string
{
    static $detected = false;
    if ($detected !== false) {
        return $detected === '' ? null : $detected;
    }
    $found = app_find_orders_column($pdo, ['order_meta_json']);
    $detected = $found ?? '';
    return $found;
}

function app_orders_meta_column(PDO $pdo): ?string
{
    return app_detect_orders_meta_column($pdo);
}

function app_detect_orders_date_column(PDO $pdo): string
{
    static $detected = null;
    if ($detected !== null) {
        return $detected;
    }
    $detected = app_find_orders_column($pdo, ['order_date', 'date']) ?? 'order_date';
    return $detected;
}

function app_orders_date_column(PDO $pdo): string
{
    return app_detect_orders_date_column($pdo);
}

function app_orders_select_fields(PDO $pdo): string
{
    $itemsColumn = app_detect_orders_items_column($pdo);
    $metaColumn = app_detect_orders_meta_column($pdo);
    $dateColumn = app_detect_orders_date_column($pdo);
    $metaSelect = $metaColumn !== null ? $metaColumn : 'NULL AS order_meta_json';
    $createdAtColumn = app_find_orders_column($pdo, ['created_at']);
    $updatedAtColumn = app_find_orders_column($pdo, ['updated_at']);
    $customerIdColumn = app_find_orders_column($pdo, ['customer_id']);
    $projectIdColumn = app_find_orders_column($pdo, ['project_id']);
    $projectContactIdColumn = app_find_orders_column($pdo, ['project_contact_id']);
    $createdAtSelect = $createdAtColumn !== null ? $createdAtColumn : 'NULL AS created_at';
    $updatedAtSelect = $updatedAtColumn !== null ? $updatedAtColumn : 'NULL AS updated_at';
    $customerIdSelect = $customerIdColumn !== null ? $customerIdColumn : 'NULL AS customer_id';
    $projectIdSelect = $projectIdColumn !== null ? $projectIdColumn : 'NULL AS project_id';
    $projectContactIdSelect = $projectContactIdColumn !== null ? $projectContactIdColumn : 'NULL AS project_contact_id';

    if ($itemsColumn === 'items') {
        return 'id, order_code, customer_name, phone, ' . $customerIdSelect . ', ' . $projectIdSelect . ', ' . $projectContactIdSelect . ', ' . $dateColumn . ' AS order_date, total, status, items AS items_json, ' . $metaSelect . ', ' . $createdAtSelect . ', ' . $updatedAtSelect;
    }

    return 'id, order_code, customer_name, phone, ' . $customerIdSelect . ', ' . $projectIdSelect . ', ' . $projectContactIdSelect . ', ' . $dateColumn . ' AS order_date, total, status, items_json, ' . $metaSelect . ', ' . $createdAtSelect . ', ' . $updatedAtSelect;
}

function app_orders_sort_clause(PDO $pdo): string
{
    static $clause = null;
    if ($clause !== null) {
        return $clause;
    }

    try {
        $stmt = $pdo->query("SHOW COLUMNS FROM orders LIKE 'created_at'");
        if ($stmt && $stmt->fetch()) {
            $clause = 'created_at DESC, id DESC';
            return $clause;
        }
    } catch (Throwable $e) {
        // Fall through to id-based sorting.
    }

    $clause = 'id DESC';
    return $clause;
}

function app_read_catalog(PDO $pdo)
{
    try {
        app_ensure_system_settings_table($pdo);
        $stmt = $pdo->prepare('SELECT setting_value FROM system_settings WHERE setting_key = :k LIMIT 1');
        $stmt->execute(['k' => 'catalog']);
        $row = $stmt->fetch();
    } catch (Throwable $e) {
        return null;
    }

    if (!$row || !isset($row['setting_value'])) {
        return null;
    }

    $decoded = json_decode((string)$row['setting_value'], true);
    if (!is_array($decoded)) {
        return null;
    }

    $billing = is_array($decoded['billing'] ?? null) ? $decoded['billing'] : [];
    $rawPaymentMethods = is_array($billing['paymentMethods'] ?? null) ? $billing['paymentMethods'] : app_payment_method_defaults();
    $paymentMethods = array_values(array_unique(array_map('app_normalize_payment_method', $rawPaymentMethods)));
    if ($paymentMethods === []) {
        $paymentMethods = app_payment_method_defaults();
    }

    $decoded['billing'] = [
        'priceFloorPercent' => max(1, min(100, (int)($billing['priceFloorPercent'] ?? 90))),
        'taxDefaultEnabled' => (bool)($billing['taxDefaultEnabled'] ?? false),
        'taxRate' => max(0, min(100, (int)($billing['taxRate'] ?? 10))),
        'paymentMethods' => $paymentMethods,
    ];

    return $decoded;
}
