export const INVENTORY_CATEGORY_OPTIONS = [
  { value: 'raw_glass', label: 'جام شیشه خام' },
  { value: 'processed_glass', label: 'شیشه فرآوری شده' },
  { value: 'hardware', label: 'یراق آلات' },
  { value: 'consumable', label: 'مصرفی' },
]

export const INVENTORY_UNIT_OPTIONS = [
  { value: 'sheet', label: 'برگ' },
  { value: 'm2', label: 'متر مربع' },
  { value: 'piece', label: 'عدد' },
  { value: 'set', label: 'ست' },
  { value: 'box', label: 'بسته' },
  { value: 'pack', label: 'پک' },
  { value: 'tube', label: 'تیوب' },
  { value: 'carton', label: 'کارتن' },
  { value: 'kg', label: 'کیلوگرم' },
  { value: 'meter', label: 'متر طول' },
  { value: 'roll', label: 'رول' },
  { value: 'liter', label: 'لیتر' },
]

export const DEFAULT_INVENTORY_ITEMS = [
  {
    title: 'جام شفاف 4 میل 2250×3210',
    category: 'raw_glass',
    baseUnit: 'sheet',
    secondaryUnit: 'm2',
    secondaryPerBase: 7.223,
    glassWidthMm: 2250,
    glassHeightMm: 3210,
    glassThicknessMm: 4,
    glassColor: 'شفاف',
  },
  {
    title: 'جام شفاف 6 میل 2250×3210',
    category: 'raw_glass',
    baseUnit: 'sheet',
    secondaryUnit: 'm2',
    secondaryPerBase: 7.223,
    glassWidthMm: 2250,
    glassHeightMm: 3210,
    glassThicknessMm: 6,
    glassColor: 'شفاف',
  },
  {
    title: 'جام برنز 6 میل 2250×3210',
    category: 'raw_glass',
    baseUnit: 'sheet',
    secondaryUnit: 'm2',
    secondaryPerBase: 7.223,
    glassWidthMm: 2250,
    glassHeightMm: 3210,
    glassThicknessMm: 6,
    glassColor: 'برنز',
  },
  {
    title: 'جام دودی 6 میل 2250×3210',
    category: 'raw_glass',
    baseUnit: 'sheet',
    secondaryUnit: 'm2',
    secondaryPerBase: 7.223,
    glassWidthMm: 2250,
    glassHeightMm: 3210,
    glassThicknessMm: 6,
    glassColor: 'دودی',
  },
  {
    title: 'جام سوپرکلیر 8 میل 2250×3210',
    category: 'raw_glass',
    baseUnit: 'sheet',
    secondaryUnit: 'm2',
    secondaryPerBase: 7.223,
    glassWidthMm: 2250,
    glassHeightMm: 3210,
    glassThicknessMm: 8,
    glassColor: 'سوپرکلیر',
  },
  {
    title: 'جام رفلکس نقره ای 6 میل 2250×3210',
    category: 'raw_glass',
    baseUnit: 'sheet',
    secondaryUnit: 'm2',
    secondaryPerBase: 7.223,
    glassWidthMm: 2250,
    glassHeightMm: 3210,
    glassThicknessMm: 6,
    glassColor: 'رفلکس نقره ای',
  },
  {
    title: 'جام لمینت خام 4+4 میل 2250×3210',
    category: 'raw_glass',
    baseUnit: 'sheet',
    secondaryUnit: 'm2',
    secondaryPerBase: 7.223,
    glassWidthMm: 2250,
    glassHeightMm: 3210,
    glassThicknessMm: 8,
    glassColor: 'شفاف',
  },
  {
    title: 'جام سکوریت خام 10 میل 2250×3210',
    category: 'raw_glass',
    baseUnit: 'sheet',
    secondaryUnit: 'm2',
    secondaryPerBase: 7.223,
    glassWidthMm: 2250,
    glassHeightMm: 3210,
    glassThicknessMm: 10,
    glassColor: 'شفاف',
  },
  {
    title: 'جام ساتینا 6 میل 2250×3210',
    category: 'raw_glass',
    baseUnit: 'sheet',
    secondaryUnit: 'm2',
    secondaryPerBase: 7.223,
    glassWidthMm: 2250,
    glassHeightMm: 3210,
    glassThicknessMm: 6,
    glassColor: 'ساتینا',
  },
  {
    title: 'جام آبی 6 میل 2250×3210',
    category: 'raw_glass',
    baseUnit: 'sheet',
    secondaryUnit: 'm2',
    secondaryPerBase: 7.223,
    glassWidthMm: 2250,
    glassHeightMm: 3210,
    glassThicknessMm: 6,
    glassColor: 'آبی',
  },
  {
    title: 'جام سبز 6 میل 2250×3210',
    category: 'raw_glass',
    baseUnit: 'sheet',
    secondaryUnit: 'm2',
    secondaryPerBase: 7.223,
    glassWidthMm: 2250,
    glassHeightMm: 3210,
    glassThicknessMm: 6,
    glassColor: 'سبز',
  },
  {
    title: 'جام شفاف 10 میل 2140×3300',
    category: 'raw_glass',
    baseUnit: 'sheet',
    secondaryUnit: 'm2',
    secondaryPerBase: 7.062,
    glassWidthMm: 2140,
    glassHeightMm: 3300,
    glassThicknessMm: 10,
    glassColor: 'شفاف',
  },
  {
    title: 'شیشه سکوریت 10 میل سفارشی',
    category: 'processed_glass',
    baseUnit: 'm2',
    secondaryUnit: 'sheet',
    secondaryPerBase: 1,
  },
  {
    title: 'شیشه دوجداره 24 میلی متر',
    category: 'processed_glass',
    baseUnit: 'm2',
    secondaryUnit: 'sheet',
    secondaryPerBase: 1,
  },
  {
    title: 'شیشه لمینت 8.8 میلی متر',
    category: 'processed_glass',
    baseUnit: 'm2',
    secondaryUnit: 'sheet',
    secondaryPerBase: 1,
  },
  {
    title: 'شیشه سندبلاست طرح دار',
    category: 'processed_glass',
    baseUnit: 'm2',
    secondaryUnit: 'sheet',
    secondaryPerBase: 1,
  },
  {
    title: 'یراق درب کشویی سری A',
    category: 'hardware',
    baseUnit: 'set',
    secondaryUnit: 'box',
    secondaryPerBase: 20,
  },
  {
    title: 'اسپایدر 4 بازو استیل',
    category: 'hardware',
    baseUnit: 'piece',
    secondaryUnit: 'box',
    secondaryPerBase: 4,
  },
  {
    title: 'چسب سیلیکون صنعتی',
    category: 'consumable',
    baseUnit: 'tube',
    secondaryUnit: 'carton',
    secondaryPerBase: 24,
  },
  {
    title: 'پد پولیش شیشه',
    category: 'consumable',
    baseUnit: 'piece',
    secondaryUnit: 'pack',
    secondaryPerBase: 10,
  },
]
